CREATE TABLE  "TBL_LOGIN" 
   (	"ID" NUMBER, 
	"KULLANICI_ADI" NVARCHAR2(100), 
	"SIFRE" NVARCHAR2(100), 
	"YETKI_ID" NUMBER, 
	"FOTOGRAF" VARCHAR2(100), 
	 CONSTRAINT "TBL_LOGIN_PK" PRIMARY KEY ("ID") ENABLE
   )