CREATE TABLE  "TBL_USERLOGIN" 
   (	"ID" NUMBER, 
	"USERNAME" NVARCHAR2(100), 
	"PASSWORD" NVARCHAR2(100), 
	"AUTHORIZATION_ID" NUMBER, 
	"PHOTO" NVARCHAR2(1000), 
	 CONSTRAINT "TBL_USERLOGIN_PK" PRIMARY KEY ("ID") ENABLE
   )