CREATE TABLE  "TBL_PATIENTS" 
   (	"ID" NUMBER, 
	"NAME" NVARCHAR2(100), 
	"SURNAME" NVARCHAR2(100), 
	"TC_IDENTITY" NVARCHAR2(100), 
	"DATE_OF_BIRTH" NVARCHAR2(100), 
	"MOBILE_PHONE" NVARCHAR2(100), 
	"ADDRESS" NVARCHAR2(100), 
	"PLACE_OF_BIRTH" NVARCHAR2(100), 
	"TOWN" NVARCHAR2(100), 
	 CONSTRAINT "TBL_PATIENTS_PK" PRIMARY KEY ("ID") ENABLE
   )