CREATE TABLE  "TBL_TRANSACTIONS" 
   (	"ROW_ID" NUMBER, 
	"PATIENTS_ID" NUMBER, 
	"DATE_OF_INSPECTION" NVARCHAR2(100), 
	"DOCTORS_ID" NUMBER, 
	"TREATMENT_ID" NUMBER, 
	"NOTES" NVARCHAR2(1000), 
	 CONSTRAINT "TBL_TRANSACTIONS_PK" PRIMARY KEY ("ROW_ID") ENABLE
   )