CREATE TABLE  "TBL_PERSONNEL" 
   (	"ID" NUMBER, 
	"TC_IDENTITY" NVARCHAR2(100), 
	"REGISTER_IDENTITY" NVARCHAR2(100), 
	"AUTHORIZATION_ID" NUMBER, 
	"NAME" NVARCHAR2(100), 
	"SURNAME" NVARCHAR2(100), 
	"MISSON" NVARCHAR2(100), 
	"DEPARTMENT" NVARCHAR2(100), 
	 CONSTRAINT "TBL_PERSONNEL_PK" PRIMARY KEY ("ID") ENABLE
   )